services:
  payload:
    image: node:22-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@10.34.3 --activate && pnpm install && pnpm dev"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:Tuan1901@db:5432/payload-cmd-test

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tuan1901
      POSTGRES_DB: payload-cmd-test
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  node_modules:

